### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by DaniW42** [makanakoeln/lnd#1]
**When I run:** 
`python3.5 lnd_connect_peers.py `

**I get:**
Traceback (most recent call last):
  File "lnd_connect_peers.py", line 19, in <module>
    peers       = json.loads(process.communicate()[0])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**When I run:**
`python lnd_connect_peers.py `

**I get:**
Traceback (most recent call last):
  File "lnd_connect_peers.py", line 3, in <module>
    import requests, subprocess, json, sys, os, logging
ImportError: No module named requests

**Comment by makanakoeln** [comment]
Hi DaniW42,

`python lnd_connect_peers.py`

should work, do you have "requests" module installed?

`pip install requests`
